name: Package JGAAP

on:
  push:
    branches: [ "gradle" ]
  pull_request:
    types:
      - closed

jobs:
  build-windows-installer:
    name: Build Installer on Windows
    runs-on: windows-latest
    steps:

# SETUP BUILD ENVIRONMENT
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v4
    - id: setup-jdk
      name: Setup JDK
      uses: actions/setup-java@v4
      with:
        java-package: jdk+fx
        architecture: x64
        distribution: 'temurin'
        java-version: '21'

# BUILD FOR DISTRIBUTION
    - id: build
      name: Build distribution
      run: ./gradlew jpackage

# SAVE INSTALLER
    - id: upload-installer
      name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        path: ./jgaap/build/jpackage/JGAAP-x86_64-9.0.0.msi
        name: windows-installer
        retention-days: 1
        
  build-macos-intel-installer:
    name: Build Installer on macOS intel
    runs-on: macos-13
    steps:

# SETUP BUILD ENVIRONMENT
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v4
    - id: setup-jdk
      name: Setup JDK
      uses: actions/setup-java@v4
      with:
        java-package: jdk+fx
        architecture: x64
        distribution: 'temurin'
        java-version: '21'

# BUILD FOR DISTRIBUTION
    - id: build
      name: Build distribution
      run: ./gradlew jpackage

# SAVE INSTALLER
    - id: upload-installer
      name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        path: ./jgaap/build/jpackage/JGAAP-x86_64-9.0.0.dmg
        name: macOS-dmg-Intel
        retention-days: 1
        
  build-macos-AS-installer:
    name: Build Installer on macOS ARM
    runs-on: macos-latest
    steps:

# SETUP BUILD ENVIRONMENT
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v4
    - id: setup-jdk
      name: Setup JDK
      uses: actions/setup-java@v4
      with:
        java-package: jdk+fx
        architecture: aarch64
        distribution: 'temurin'
        java-version: '21'

# BUILD FOR DISTRIBUTION
    - id: build
      name: Build distribution
      run: ./gradlew jpackage

# SAVE INSTALLER
    - id: upload-installer
      name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        path: ./jgaap/build/jpackage/JGAAP-aarch64-9.0.0.dmg
        name: macOS-dmg-AS
        retention-days: 1

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-windows-installer,  build-macos-AS-installer,  build-macos-intel-installer]
    steps:

# DOWNLOAD INSTALLERS
    - id: download-macos-intel-installer
      name: Download Linux installer
      uses: actions/download-artifact@v4
      with:
        name: macOS-dmg-Intel

    - id: download-macos-arm-installer
      name: Download Linux installer
      uses: actions/download-artifact@v4
      with:
        name: macOS-dmg-AS

    - id: download-windows-installer
      name: Download Windows installer
      uses: actions/download-artifact@v4
      with:
        name: windows-installer

# CREATE GITHUB RELEASE AND ADD ASSETS
    - id: tag
      name: Move example-release tag
      shell: bash
      if: false
      run: |
        # Move tag
        git tag -d example-release
        git push --delete origin example-release
        git tag -a example-release -m "Example of a Release"
        git push --follow-tags
    - id: create-release
      name: Create GitHub release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: example-release
        release_name: example-release
        draft: false
        prerelease: false
    - id: release-macOS-Intel
      name: Release macOS Intel installer
      uses: actions/upload-release-asset@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: JGAAP-x86_64-9.0.0.dmg
        asset_name: JGAAP-x86_64-9.0.0.dmg
        asset_content_type: application/x-binary
    - id: release-macOS-AS
      name: Release macOS AS installer
      uses: actions/upload-release-asset@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: JGAAP-aarch64-9.0.0.dmg
        asset_name: JGAAP-aarch64-9.0.0.dmg
        asset_content_type: application/x-binary
    - id: release-windows-installer
      name: Release Windows installer
      uses: actions/upload-release-asset@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: JGAAP-x86_64-9.0.0.msi
        asset_name: JGAAP-x86_64-9.0.0.msi
        asset_content_type: application/x-binary
